### ISSUE TITLE
Box appears, but point does not appear

### ISSUE THREAD

**Issue by ykn96** [Elin24/cclabeler#16]
Hello @Elin24 thank you for developing this tool. I used it for awhile and then suddenly i realise my boxes are appearing, but then the point do not appear. 

![Screenshot from 2023-08-17 10-43-03](https://github.com/Elin24/cclabeler/assets/93758179/7d989516-a20a-44d3-af66-a87d67666704)

![Screenshot from 2023-08-17 10-23-38](https://github.com/Elin24/cclabeler/assets/93758179/7c3f279a-8c41-4a16-8cca-635f888fc8e3)

I am not sure why either. It used to work before this.

here is my pip list
```
Package                      Version
---------------------------- ------------
absl-py                      1.4.0
altgraph                     0.17.3
asgiref                      3.6.0
astunparse                   1.6.3
bleach                       6.0.0
build                        0.10.0
cachetools                   5.3.0
certifi                      2023.7.22
cffi                         1.15.1
charset-normalizer           3.1.0
colorama                     0.4.6
cryptography                 41.0.3
Django                       3.2.18
docutils                     0.20.1
easydict                     1.10
flatbuffers                  23.3.3
gast                         0.4.0
google-auth                  2.17.3
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.54.0
h5py                         3.8.0
idna                         3.4
importlib-metadata           6.5.0
jaraco.classes               3.3.0
jeepney                      0.8.0
keras                        2.11.0
keyring                      24.2.0
libclang                     16.0.0
Markdown                     3.4.3
markdown-it-py               3.0.0
MarkupSafe                   2.1.2
mdurl                        0.1.2
more-itertools               10.1.0
numpy                        1.21.6
oauthlib                     3.2.2
opencv-python                4.7.0.72
opt-einsum                   3.3.0
packaging                    23.1
pandas                       1.3.5
Pillow                       9.5.0
pip                          23.2.1
pkginfo                      1.9.6
protobuf                     3.19.6
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycparser                    2.21
Pygments                     2.16.1
pyinstaller                  5.13.0
pyinstaller-hooks-contrib    2023.6
pyproject_hooks              1.0.0
python-dateutil              2.8.2
pytz                         2023.3
PyYAML                       6.0
readme-renderer              40.0
requests                     2.28.2
requests-oauthlib            1.3.1
requests-toolbelt            1.0.0
rfc3986                      2.0.0
rich                         13.5.2
rsa                          4.9
scipy                        1.7.3
SecretStorage                3.3.3
setuptools                   58.1.0
six                          1.16.0
sqlparse                     0.4.4
tensorboard                  2.11.2
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorboardX                 2.6
tensorflow                   2.11.0
tensorflow-estimator         2.11.0
tensorflow-intel             0.0.1
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.2.0
tomli                        2.0.1
torch                        1.13.1+cu117
torchaudio                   0.13.1+cu117
torchvision                  0.1.6
tqdm                         4.65.0
twine                        4.0.2
typing_extensions            4.4.0
urllib3                      1.26.15
webencodings                 0.5.1
Werkzeug                     2.2.3
wheel                        0.41.1
wincertstore                 0.2
wrapt                        1.15.0
yacs                         0.1.8
zipp                         3.15.0
```

Do you know why?

**Comment by Elin24** [comment]
It's not clear. Is there any information presented in your terminal or DevTools in your browser?

**Comment by ykn96** [comment]
I used terminal to launch

```
Go to: http://localhost:8000/
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 21, 2023 - 08:35:43
Django version 3.2.18, using settings 'CCLabeler.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[21/Aug/2023 08:35:50] "GET /label HTTP/1.1" 200 2278
[21/Aug/2023 08:35:52] "POST /table HTTP/1.1" 200 8542
Not Found: /favicon.ico
[21/Aug/2023 08:35:52] "GET /favicon.ico HTTP/1.1" 404 2644
[21/Aug/2023 08:36:09] "GET /table HTTP/1.1" 200 2278
[21/Aug/2023 08:36:10] "POST /table HTTP/1.1" 200 8542
[21/Aug/2023 08:36:13] "POST /label HTTP/1.1" 200 5456
[21/Aug/2023 08:36:13] "GET /static/Pairs_DJI_20221202230210_0003_T_frame120.jpg HTTP/1.1" 200 94825
[21/Aug/2023 08:36:32] "POST /label HTTP/1.1" 200 33546
[21/Aug/2023 08:36:32] "GET /static/Pairs_DJI_20221202230210_0003_Z_frame120.jpg HTTP/1.1" 200 870848
[21/Aug/2023 08:37:48] "GET /static/jquery.min.map HTTP/1.1" 404 1801
[21/Aug/2023 08:37:48] "GET /static/bootstrap.min.css.map HTTP/1.1" 404 1822
[21/Aug/2023 08:38:38] "GET /label HTTP/1.1" 200 2278
[21/Aug/2023 08:38:38] "GET /static/login.css HTTP/1.1" 200 747
[21/Aug/2023 08:38:38] "GET /static/bootstrap.min.js HTTP/1.1" 200 37051
[21/Aug/2023 08:38:38] "GET /static/jquery.mousewheel.min.js HTTP/1.1" 200 2778
[21/Aug/2023 08:38:38] "GET /static/bootstrap.min.css HTTP/1.1" 200 121205
[21/Aug/2023 08:38:38] "GET /static/jquery.min.js HTTP/1.1" 200 84284
[21/Aug/2023 08:38:38] "GET /static/icon-white.svg HTTP/1.1" 200 2303
[21/Aug/2023 08:38:38] "GET /static/favicon.ico HTTP/1.1" 200 67646
[21/Aug/2023 08:38:40] "POST /table HTTP/1.1" 200 8542
[21/Aug/2023 08:38:40] "GET /static/bootstrap-slider.min.css HTTP/1.1" 200 4885
[21/Aug/2023 08:38:40] "GET /static/bootstrap-slider.min.js HTTP/1.1" 200 21199
[21/Aug/2023 08:38:41] "POST /label HTTP/1.1" 200 45346
[21/Aug/2023 08:38:41] "GET /static/style.css HTTP/1.1" 200 752
[21/Aug/2023 08:38:41] "GET /static/icon-blue.svg HTTP/1.1" 200 2303
[21/Aug/2023 08:38:41] "GET /static/global.js HTTP/1.1" 200 12661
[21/Aug/2023 08:38:41] "GET /static/label.js HTTP/1.1" 200 6407
[21/Aug/2023 08:38:41] "GET /static/button.js HTTP/1.1" 200 9974
[21/Aug/2023 08:38:41] "GET /static/oldimg.svg HTTP/1.1" 200 679
[21/Aug/2023 08:38:41] "GET /static/load.svg HTTP/1.1" 200 2494
[21/Aug/2023 08:38:41] "GET /static/newimg.svg HTTP/1.1" 200 678
[21/Aug/2023 08:38:41] "GET /static/rectangle.svg HTTP/1.1" 200 636
[21/Aug/2023 08:38:41] "GET /static/rectify.svg HTTP/1.1" 200 772
[21/Aug/2023 08:38:41] "GET /static/point.svg HTTP/1.1" 200 594
[21/Aug/2023 08:38:41] "GET /static/Pairs_DJI_20221203004356_0002_Z_frame780.jpg HTTP/1.1" 200 1072974
```

Doesnt seem to be anything wrong. Today my chrome just updated and now both chrome and firefox cannot see the dots!

From the console when i click on inspect within google chrome
```
run
DevTools failed to load source map: Could not load content for chrome-extension://mlomiejdfkolichcflejclcbmpeaniij/dist/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for http://localhost:8000/static/jquery.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8000/static/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
global.js:412 Uncaught TypeError: save is not a function
    at global.js:412:9
```

**Comment by Elin24** [comment]
Can you press ctrl+F5 and then paste the inspect's output here?

**Comment by ykn96** [comment]
Outputs in the console
```
global.js:412 Uncaught TypeError: save is not a function
    at global.js:412:9
179global.js:402 run
DevTools failed to load source map: Could not load content for chrome-extension://mlomiejdfkolichcflejclcbmpeaniij/dist/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for http://localhost:8000/static/jquery.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8000/static/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
2global.js:412 Uncaught TypeError: save is not a function
    at global.js:412:9
```

If i try to click on label, then add dots, no errors seems to be triggered by label.js

Could you telll me which element to inspect?

**Comment by Elin24** [comment]
I updated `button.js` to solve the problem `Uncaught TypeError:  save is not a function at global.js:412:9`.

I noticed that your Chrome and Firefox are updated to the newest one. Maybe there is something different in the new Chrome. However, I did not meet your problem on my device. The version of my Chrome is `115.0.5790.170`, you can update your Chrome to a validated version.

If you still want to check which part meets the problem, the `DrawPoint` function is located in Line-149 of `global.js`, you can write a log message, e.g., `console.log(x, y);` to show whether this function works.

You can paste your observation here. I will answer it if I have any ideas.

**Comment by mpmmpmmmp** [comment]
You need to update the file /js/global.js:
function drawPoint(context, x, y, color = '#f00', radius = 1) {
    context.beginPath();
    context.arc(x, y, radius, 0, 2 * Math.PI);
    context.fillStyle = color;
    context.fill();
    context.closePath();
}

**Comment by ykn96** [comment]
@mpmmpmmmp hey i tried updating my global.js to your codes but still doesnt work. My dots do not appear, but the bounding box will appear.

**Comment by ykn96** [comment]
@Elin24  

![Screenshot from 2024-02-05 15-20-11](https://github.com/Elin24/cclabeler/assets/93758179/d703844e-0e80-4199-a6ed-f153879c32eb)

I added a few console.log lines 
```
    console.log(x, y);
    console.log(width);
```
However, despite adding these console log lines, no output is given to the console for drawing the points. It seems like in global.js the function "drawPoint" is not accessed at all. and at line 261 function Point is not called.

In contrast, when drawing bounding boxes
![image](https://github.com/Elin24/cclabeler/assets/93758179/69d0ddbe-c45f-4a65-b64d-e728c47fa245)
it shows that function Box (line 199 onwards) is being called. 

Any idea why?

**Comment by ykn96** [comment]
@Elin24  is it also normal for ```drawStackDict``` to be using normalised values?

```
 var initMarkStatus = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
        var drawStackDict = JSON.parse("[{&quot;x&quot;: 0.5515625, &quot;y&quot;: 0.028703703703703703}, {&quot;x&quot;: 0.55625, &quot;y&quot;: 0.04537037037037037}, {&quot;x&quot;: 0.5723958333333333, &quot;y&quot;: 0.05925925925925926}, {&quot;x&quot;: 0.5822916666666667, &quot;y&quot;: 0.06296296296296296}, {&quot;x&quot;: 0.6041666666666666, &quot;y&quot;: 0.06851851851851852}, {&quot;x&quot;: 0.5682291666666667, &quot;y&quot;: 0.06574074074074074}, {&quot;x&quot;: 0.6260416666666667, &quot;y&quot;: 0.07407407407407407}, {&quot;x&quot;: 0.5848958333333333, &quot;y&quot;: 0.08148148148148149}, {&quot;x&quot;: 0.6067708333333334, &quot;y&quot;: 0.08518518518518518}, {&quot;x&quot;: 0.6416666666666667, &quot;y&quot;: 0.09166666666666666}, {&quot;x&quot;: 0.6078125, &quot;y&quot;: 0.10185185185185185}, {&quot;x&quot;: 0.5880208333333333, &quot;y&quot;: 0.09907407407407408}, {&quot;x&quot;: 0.6244791666666667, &quot;y&quot;: 0.10185185185185185}, {&quot;x&quot;: 0.47604166666666664, &quot;y&quot;: 0.1037037037037037}, {&quot;x&quot;: 0.6161458333333333, &quot;y&quot;: 0.10833333333333334}, {&quot;x&quot;: 0.6489583333333333, &quot;y&quot;: 0.11296296296296296}, {&quot;x&quot;: 0.6036458333333333, &quot;y&quot;: 0.12037037037037036}, {&quot;x&quot;: 0.56875, &quot;y&quot;: 0.11851851851851852}, {&quot;x&quot;: 0.43854166666666666, &quot;y&quot;: 0.1287037037037037}, {&quot;x&quot;: 0.446875, &quot;y&quot;: 0.12685185185185185}, {&quot;x&quot;: 0.7421875, &quot;y&quot;: 0.13240740740740742}, {&quot;x&quot;: 0.6671875, &quot;y&quot;: 0.13518518518518519}, {&quot;x&quot;: 0.41458333333333336, &quot;y&quot;: 0.13796296296296295}, {&quot;x&quot;: 0.4395833333333333, &quot;y&quot;: 0.14537037037037037}, {&quot;x&quot;: 0.6125, &quot;y&quot;: 0.14537037037037037}, {&quot;x&quot;: 0.6359375, &quot;y&quot;: 0.1388888888888889}, {&quot;x&quot;: 0.3984375, &quot;y&quot;: 0.14351851851851852}, {&quot;x&quot;: 0.6338541666666667, &quot;y&quot;: 0.14537037037037037}, {&quot;x&quot;: 0.4239583333333333, &quot;y&quot;: 0.14351851851851852}, {&quot;x&quot;: 0.4515625, &quot;y&quot;: 0.14814814814814814}, {&quot;x&quot;: 0.3890625, &quot;y&quot;: 0.15185185185185185}, {&quot;x&quot;: 0.5973958333333333, &quot;y&quot;: 0.14907407407407408}, {&quot;x&quot;: 0.5854166666666667, &quot;y&quot;: 0.15092592592592594}, {&quot;x&quot;: 0.4088541666666667, &quot;y&quot;: 0.15833333333333333}, {&quot;x&quot;: 0.43072916666666666, &quot;y&quot;: 0.1527777777777778}, {&quot;x&quot;: 0.6046875, &quot;y&quot;: 0.15833333333333333}, {&quot;x&quot;: 0.509375, &quot;y&quot;: 0.1574074074074074}, {&quot;x&quot;: 0.3765625, &quot;y&quot;: 0.16111111111111112}, {&quot;x&quot;: 0.5359375, &quot;y&quot;: 0.16203703703703703}, {&quot;x&quot;: 0.39739583333333334, &quot;y&quot;: 0.1648148148148148}, {&quot;x&quot;: 0.596875, &quot;y&quot;: 0.16018518518518518}, {&quot;x&quot;: 0.5046875, &quot;y&quot;: 0.1648148148148148}, {&quot;x&quot;: 0.4505208333333333, &quot;y&quot;: 0.16296296296296298}, {&quot;x&quot;: 0.6333333333333333, &quot;y&quot;: 0.16574074074074074}, {&quot;x&quot;: 0.45729166666666665, &quot;y&quot;: 0.1638888888888889}, {&quot;x&quot;: 0.43645833333333334, &quot;y&quot;: 0.17592592592592593}, {&quot;x&quot;: 0.5963541666666666, &quot;y&quot;: 0.17037037037037037}, {&quot;x&quot;: 0.4244791666666667, &quot;y&quot;: 0.17222222222222222}, {&quot;x&quot;: 0.659375, &quot;y&quot;: 0.16666666666666666}, {&quot;x&quot;: 0.6135416666666667, &quot;y&quot;: 0.17222222222222222}, {&quot;x&quot;: 0.40989583333333335, &quot;y&quot;: 0.1787037037037037}, {&quot;x&quot;: 0.3619791666666667, &quot;y&quot;: 0.17777777777777778}, {&quot;x&quot;: 0.39947916666666666, &quot;y&quot;: 0.1814814814814815}, {&quot;x&quot;: 0.3880208333333333, &quot;y&quot;: 0.18333333333333332}, {&quot;x&quot;: 0.6541666666666667, &quot;y&quot;: 0.18518518518518517}, {&quot;x&quot;: 0.7291666666666666, &quot;y&quot;: 0.18888888888888888}, {&quot;x&quot;: 0.5973958333333333, &quot;y&quot;: 0.18611111111111112}, {&quot;x&quot;: 0.37604166666666666, &quot;y&quot;: 0.19537037037037036}, {&quot;x&quot;: 0.5697916666666667, &quot;y&quot;: 0.18333333333333332}, {&quot;x&quot;: 0.7177083333333333, &quot;y&quot;: 0.18981481481481483}, {&quot;x&quot;: 0.5755208333333334, &quot;y&quot;: 0.19537037037037036}, {&quot;x&quot;: 0.6442708333333333, &quot;y&quot;: 0.18888888888888888}, {&quot;x&quot;: 0.41354166666666664, &quot;y&quot;: 0.19907407407407407}, {&quot;x&quot;: 0.4234375, &quot;y&quot;: 0.19907407407407407}, {&quot;x&quot;: 0.35208333333333336, &quot;y&quot;: 0.19074074074074074}, {&quot;x&quot;: 0.6791666666666667, &quot;y&quot;: 0.2037037037037037}, {&quot;x&quot;: 0.3963541666666667, &quot;y&quot;: 0.19537037037037036}, {&quot;x&quot;: 0.440625, &quot;y&quot;: 0.2037037037037037}, {&quot;x&quot;: 0.2552083333333333, &quot;y&quot;: 0.20555555555555555}, {&quot;x&quot;: 0.5984375, &quot;y&quot;: 0.20277777777777778}, {&quot;x&quot;: 0.35885416666666664, &quot;y&quot;: 0.2037037037037037}, {&quot;x&quot;: 0.40260416666666665, &quot;y&quot;: 0.20833333333333334}, {&quot;x&quot;: 0.7515625, &quot;y&quot;: 0.2064814814814815}, {&quot;x&quot;: 0.7958333333333333, &quot;y&quot;: 0.21203703703703702}, {&quot;x&quot;: 0.34010416666666665, &quot;y&quot;: 0.2175925925925926}, {&quot;x&quot;: 0.3692708333333333, &quot;y&quot;: 0.20925925925925926}, {&quot;x&quot;: 0.5484375, &quot;y&quot;: 0.20925925925925926}, {&quot;x&quot;: 0.5723958333333333, &quot;y&quot;: 0.21203703703703702}, {&quot;x&quot;: 0.6692708333333334, &quot;y&quot;: 0.21666666666666667}, {&quot;x&quot;: 0.5572916666666666, &quot;y&quot;: 0.21481481481481482}, {&quot;x&quot;: 0.771875, &quot;y&quot;: 0.2175925925925926}, {&quot;x&quot;: 0.36041666666666666, &quot;y&quot;: 0.22314814814814815}, {&quot;x&quot;: 0.3770833333333333, &quot;y&quot;: 0.22777777777777777}, {&quot;x&quot;: 0.4015625, &quot;y&quot;: 0.22407407407407406}, {&quot;x&quot;: 0.8427083333333333, &quot;y&quot;: 0.22407407407407406}, {&quot;x&quot;: 0.5713541666666667, &quot;y&quot;: 0.225}, {&quot;x&quot;: 0.446875, &quot;y&quot;: 0.22962962962962963}, {&quot;x&quot;: 0.4171875, &quot;y&quot;: 0.23425925925925925}, {&quot;x&quot;: 0.3328125, &quot;y&quot;: 0.23148148148148148}, {&quot;x&quot;: 0.7166666666666667, &quot;y&quot;: 0.22870370370370371}, {&quot;x&quot;: 0.6494791666666667, &quot;y&quot;: 0.23425925925925925}, {&quot;x&quot;: 0.7979166666666667, &quot;y&quot;: 0.2361111111111111}, {&quot;x&quot;: 0.42916666666666664, &quot;y&quot;: 0.2388888888888889}, {&quot;x&quot;: 0.740625, &quot;y&quot;: 0.23703703703703705}, {&quot;x&quot;: 0.3859375, &quot;y&quot;: 0.24074074074074073}, {&quot;x&quot;: 0.8354166666666667, &quot;y&quot;: 0.23703703703703705}, {&quot;x&quot;: 0.31927083333333334, &quot;y&quot;: 0.23981481481481481}, {&quot;x&quot;: 0.39947916666666666, &quot;y&quot;: 0.24444444444444444}, {&quot;x&quot;: 0.3734375, &quot;y&quot;: 0.25277777777777777}, {&quot;x&quot;: 0.3541666666666667, &quot;y&quot;: 0.24814814814814815}, {&quot;x&quot;: 0.7088541666666667, &quot;y&quot;: 0.25462962962962965}, {&quot;x&quot;: 0.221875, &quot;y&quot;: 0.2574074074074074}, {&quot;x&quot;: 0.6588541666666666, &quot;y&quot;: 0.25833333333333336}, {&quot;x&quot;: 0.7994791666666666, &quot;y&quot;: 0.2574074074074074}, {&quot;x&quot;: 0.5515625, &quot;y&quot;: 0.25462962962962965}, {&quot;x&quot;: 0.5578125, &quot;y&quot;: 0.2574074074074074}, {&quot;x&quot;: 0.3072916666666667, &quot;y&quot;: 0.25833333333333336}, {&quot;x&quot;: 0.3385416666666667, &quot;y&quot;: 0.2601851851851852}, {&quot;x&quot;: 0.4166666666666667, &quot;y&quot;: 0.25833333333333336}, {&quot;x&quot;: 0.5635416666666667, &quot;y&quot;: 0.2574074074074074}, {&quot;x&quot;: 0.36354166666666665, &quot;y&quot;: 0.2611111111111111}, {&quot;x&quot;: 0.5807291666666666, &quot;y&quot;: 0.2611111111111111}, {&quot;x&quot;: 0.4036458333333333, &quot;y&quot;: 0.26666666666666666}, {&quot;x&quot;: 0.3848958333333333, &quot;y&quot;: 0.262037037037037}, {&quot;x&quot;: 0.5416666666666666, &quot;y&quot;: 0.26481481481481484}, {&quot;x&quot;: 0.25885416666666666, &quot;y&quot;: 0.26851851851851855}, {&quot;x&quot;: 0.7317708333333334, &quot;y&quot;: 0.26944444444444443}, {&quot;x&quot;: 0.7421875, &quot;y&quot;: 0.26851851851851855}, {&quot;x&quot;: 0.3140625, &quot;y&quot;: 0.2712962962962963}, {&quot;x&quot;: 0.32708333333333334, &quot;y&quot;: 0.2712962962962963}, {&quot;x&quot;: 0.42552083333333335, &quot;y&quot;: 0.27037037037037037}, {&quot;x&quot;: 0.7927083333333333, &quot;y&quot;: 0.27685185185185185}, {&quot;x&quot;: 0.6625, &quot;y&quot;: 0.2824074074074074}, {&quot;x&quot;: 0.3046875, &quot;y&quot;: 0.2824074074074074}, {&quot;x&quot;: 0.38385416666666666, &quot;y&quot;: 0.2759259259259259}, {&quot;x&quot;: 0.28020833333333334, &quot;y&quot;: 0.2814814814814815}, {&quot;x&quot;: 0.3453125, &quot;y&quot;: 0.2796296296296296}, {&quot;x&quot;: 0.8645833333333334, &quot;y&quot;: 0.2851851851851852}, {&quot;x&quot;: 0.2890625, &quot;y&quot;: 0.2814814814814815}, {&quot;x&quot;: 0.4161458333333333, &quot;y&quot;: 0.2861111111111111}, {&quot;x&quot;: 0.5848958333333333, &quot;y&quot;: 0.28425925925925927}, {&quot;x&quot;: 0.965625, &quot;y&quot;: 0.28888888888888886}, {&quot;x&quot;: 0.6020833333333333, &quot;y&quot;: 0.287962962962963}, {&quot;x&quot;: 0.5427083333333333, &quot;y&quot;: 0.28888888888888886}, {&quot;x&quot;: 0.2671875, &quot;y&quot;: 0.2953703703703704}, {&quot;x&quot;: 0.32395833333333335, &quot;y&quot;: 0.2935185185185185}, {&quot;x&quot;: 0.33697916666666666, &quot;y&quot;: 0.2935185185185185}, {&quot;x&quot;: 0.34739583333333335, &quot;y&quot;: 0.29444444444444445}, {&quot;x&quot;: 0.29635416666666664, &quot;y&quot;: 0.30185185185185187}, {&quot;x&quot;: 0.4265625, &quot;y&quot;: 0.2953703703703704}, {&quot;x&quot;: 0.6510416666666666, &quot;y&quot;: 0.30462962962962964}, {&quot;x&quot;: 0.6828125, &quot;y&quot;: 0.3037037037037037}, {&quot;x&quot;: 0.88125, &quot;y&quot;: 0.3074074074074074}, {&quot;x&quot;: 0.3572916666666667, &quot;y&quot;: 0.30925925925925923}, {&quot;x&quot;: 0.15572916666666667, &quot;y&quot;: 0.31574074074074077}, {&quot;x&quot;: 0.7255208333333333, &quot;y&quot;: 0.3074074074074074}, {&quot;x&quot;: 0.7072916666666667, &quot;y&quot;: 0.3101851851851852}, {&quot;x&quot;: 0.25104166666666666, &quot;y&quot;: 0.31574074074074077}, {&quot;x&quot;: 0.3078125, &quot;y&quot;: 0.31296296296296294}, {&quot;x&quot;: 0.690625, &quot;y&quot;: 0.3138888888888889}, {&quot;x&quot;: 0.41770833333333335, &quot;y&quot;: 0.32037037037037036}, {&quot;x&quot;: 0.28854166666666664, &quot;y&quot;: 0.3138888888888889}, {&quot;x&quot;: 0.2984375, &quot;y&quot;: 0.3194444444444444}, {&quot;x&quot;: 0.4515625, &quot;y&quot;: 0.31574074074074077}, {&quot;x&quot;: 0.6770833333333334, &quot;y&quot;: 0.31851851851851853}, {&quot;x&quot;: 0.2791666666666667, &quot;y&quot;: 0.33425925925925926}, {&quot;x&quot;: 0.7213541666666666, &quot;y&quot;: 0.32222222222222224}, {&quot;x&quot;: 0.7088541666666667, &quot;y&quot;: 0.325}, {&quot;x&quot;: 0.8765625, &quot;y&quot;: 0.3194444444444444}, {&quot;x&quot;: 0.22916666666666666, &quot;y&quot;: 0.3277777777777778}, {&quot;x&quot;: 0.6697916666666667, &quot;y&quot;: 0.32592592592592595}, {&quot;x&quot;: 0.30520833333333336, &quot;y&quot;: 0.3388888888888889}, {&quot;x&quot;: 0.384375, &quot;y&quot;: 0.3314814814814815}, {&quot;x&quot;: 0.3234375, &quot;y&quot;: 0.3472222222222222}, {&quot;x&quot;: 0.9791666666666666, &quot;y&quot;: 0.337037037037037}, {&quot;x&quot;: 0.35104166666666664, &quot;y&quot;: 0.34074074074074073}, {&quot;x&quot;: 0.23854166666666668, &quot;y&quot;: 0.3435185185185185}, {&quot;x&quot;: 0.2640625, &quot;y&quot;: 0.3416666666666667}, {&quot;x&quot;: 0.36770833333333336, &quot;y&quot;: 0.34629629629629627}, {&quot;x&quot;: 0.4348958333333333, &quot;y&quot;: 0.33796296296296297}, {&quot;x&quot;: 0.39947916666666666, &quot;y&quot;: 0.34444444444444444}, {&quot;x&quot;: 0.21979166666666666, &quot;y&quot;: 0.3472222222222222}, {&quot;x&quot;: 0.3390625, &quot;y&quot;: 0.3472222222222222}, {&quot;x&quot;: 0.7302083333333333, &quot;y&quot;: 0.34814814814814815}, {&quot;x&quot;: 0.965625, &quot;y&quot;: 0.36203703703703705}, {&quot;x&quot;: 0.2625, &quot;y&quot;: 0.3638888888888889}, {&quot;x&quot;: 0.35833333333333334, &quot;y&quot;: 0.3731481481481482}, {&quot;x&quot;: 0.3489583333333333, &quot;y&quot;: 0.3685185185185185}, {&quot;x&quot;: 0.3046875, &quot;y&quot;: 0.36944444444444446}, {&quot;x&quot;: 0.9260416666666667, &quot;y&quot;: 0.37592592592592594}, {&quot;x&quot;: 0.38125, &quot;y&quot;: 0.37222222222222223}, {&quot;x&quot;: 0.2760416666666667, &quot;y&quot;: 0.37777777777777777}, {&quot;x&quot;: 0.9494791666666667, &quot;y&quot;: 0.37592592592592594}, {&quot;x&quot;: 0.39479166666666665, &quot;y&quot;: 0.37592592592592594}, {&quot;x&quot;: 0.32864583333333336, &quot;y&quot;: 0.37962962962962965}, {&quot;x&quot;: 0.31354166666666666, &quot;y&quot;: 0.3787037037037037}, {&quot;x&quot;: 0.42083333333333334, &quot;y&quot;: 0.37592592592592594}, {&quot;x&quot;: 0.4046875, &quot;y&quot;: 0.37777777777777777}, {&quot;x&quot;: 0.18958333333333333, &quot;y&quot;: 0.3814814814814815}, {&quot;x&quot;: 0.37447916666666664, &quot;y&quot;: 0.3768518518518518}, {&quot;x&quot;: 0.28854166666666664, &quot;y&quot;: 0.387037037037037}, {&quot;x&quot;: 0.4583333333333333, &quot;y&quot;: 0.387037037037037}, {&quot;x&quot;: 0.3484375, &quot;y&quot;: 0.387037037037037}, {&quot;x&quot;: 0.46145833333333336, &quot;y&quot;: 0.39166666666666666}, {&quot;x&quot;: 0.4583333333333333, &quot;y&quot;: 0.39351851851851855}, {&quot;x&quot;: 0.46145833333333336, &quot;y&quot;: 0.39351851851851855}, {&quot;x&quot;: 0.37395833333333334, &quot;y&quot;: 0.3962962962962963}, {&quot;x&quot;: 0.4588541666666667, &quot;y&quot;: 0.39537037037037037}, {&quot;x&quot;: 0.8953125, &quot;y&quot;: 0.4046296296296296}, {&quot;x&quot;: 0.3411458333333333, &quot;y&quot;: 0.4046296296296296}, {&quot;x&quot;: 0.41041666666666665, &quot;y&quot;: 0.412962962962963}, {&quot;x&quot;: 0.475, &quot;y&quot;: 0.4046296296296296}, {&quot;x&quot;: 0.328125, &quot;y&quot;: 0.4212962962962963}, {&quot;x&quot;: 0.4265625, &quot;y&quot;: 0.41203703703703703}, {&quot;x&quot;: 0.29739583333333336, &quot;y&quot;: 0.42592592592592593}, {&quot;x&quot;: 0.4239583333333333, &quot;y&quot;: 0.41388888888888886}, {&quot;x&quot;: 0.3854166666666667, &quot;y&quot;: 0.42314814814814816}, {&quot;x&quot;: 0.4473958333333333, &quot;y&quot;: 0.4185185185185185}, {&quot;x&quot;: 0.2734375, &quot;y&quot;: 0.42407407407407405}, {&quot;x&quot;: 0.4953125, &quot;y&quot;: 0.4166666666666667}, {&quot;x&quot;: 0.4296875, &quot;y&quot;: 0.42592592592592593}, {&quot;x&quot;: 0.496875, &quot;y&quot;: 0.41944444444444445}, {&quot;x&quot;: 0.35520833333333335, &quot;y&quot;: 0.4361111111111111}, {&quot;x&quot;: 0.49635416666666665, &quot;y&quot;: 0.4212962962962963}, {&quot;x&quot;: 0.49635416666666665, &quot;y&quot;: 0.42314814814814816}, {&quot;x&quot;: 0.48125, &quot;y&quot;: 0.43425925925925923}, {&quot;x&quot;: 0.4578125, &quot;y&quot;: 0.4351851851851852}, {&quot;x&quot;: 0.4635416666666667, &quot;y&quot;: 0.45}]".replace(/&quot;/g, '"'));
```

**Comment by KZyred** [comment]
I have the same problem. Please help me! @Elin24

**Comment by Elin24** [comment]
The problem is solved by changing the way to plot a point. New code has been released [global.js:149](https://github.com/Elin24/cclabeler/blob/eadde94e149d40f77b8bfa027b29edeea9a8d656/js/global.js#L149)
